apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      serviceAccountName: runner-service-account
      containers:
        - image: samcoxg/konula:0.0.6
          name: django
          ports:
            - containerPort: 8000
