apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-role
  namespace: default
rules:
  - apiGroups:
        - batch
    resources:
      - jobs
      - jobs/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]